
#General
[general]
	#Using ticex-more-config.toml(If true, it will override your datapack!)
	useMoreConfig = true
	#MAX Rate Capacity(RF/t)
	rateCapacity = 100000
	#Fluid Transmuter valid tag prefix list
	fluid_transmuter_patterns = ["forge:"]
	#Fluid Transmuter invalid tag prefix list
	fluid_transmuter_exclude_patterns = ["forge:water", "forge:lava"]

[avaritia]
	#Probability of a neutron pile is dropped by condensing modifier
	condensingDropProbability = 0.003

[mekanism]
	#Allow Mekaplate can use shield of electricity
	mekaplateUseShield = true

[apotheosis]
	#Maximum level of enchantments granted by override
	overrideLevelLimit = 255

["ars nouveau"]
	#Internal cooldown ticks of spellcasting
	reactiveCooldown = 10

	["ars nouveau".curios]
		#Ticks remaining on the gauntlet after a gauntlet shot hits
		gantletRemainTicks = 40
		#Blacklist of entities that do not drop the glove.
		gloveDropBlacklist = ["minecraft:armor_stand", "dummmmmmy:target_dummy"]
		#Use gloveDropBlacklist as whitelist
		gloveDropBlacklistAsWhitelist = false

	#Provided by AddonAPI:
	#Other Mod Compat Options
	["ars nouveau".compat]
		"Avaritia Compat" = true
		"CC:Tweaked Compat" = true
		"Psi Compat" = true
		Default = true
		"Iron's Spells n' Spellbooks Compat" = true
		"Ars Nouveau Compat" = true
		"Apotheosis Compat" = true
		"ProjectE Compat" = true
		"SlashBlade Compat" = true
		"Draconic Evolution Compat" = true
		"Curios API Compat" = true
		"Botania Compat" = true
		"TaCz Compat" = true
		"Mekanism Compat" = true
		"Create Compat" = true
		"JEI Compat" = true

