
[general]
	#When the next EMC mapping occurs write the results to config/ProjectE/pregenerated_emc.json and only ever run the mapping again when that file does not exist, this setting is set to false, or an error occurred parsing that file.
	pregenerate = false
	#Want to take a look at the internals of EMC Calculation? Enable this to write all the conversions and setValue-Commands to config/ProjectE/mappingdump.json
	dumpEverythingToFile = false
	#Log known EMC Exploits. This can not and will not find all possible exploits. This will only find exploits that result in fixed/custom emc values that the algorithm did not overwrite. Exploits that derive from conversions that are unknown to ProjectE will not be found.
	logEMCExploits = true

[CraftingMapper]

	[CraftingMapper.BotaniaElvenTradeMapper]
		#ProjectE-Integration Recipe Mapper for Botania Elven Trade Mapper. Required Mods: [botania]
		enabled = false

	[CraftingMapper.MekPaintingMachine]
		#Maps Mekanism painting machine recipes.
		enabled = false

	[CraftingMapper.CreateDeployerApplicationMapper]
		#ProjectE-Integration Recipe Mapper for Create Deployer Application Mapper. Required Mods: [create]
		enabled = false

	[CraftingMapper.MekChemicalInfuser]
		#Maps Mekanism chemical infuser recipes.
		enabled = false

	[CraftingMapper.CreateMillingMapper]
		#ProjectE-Integration Recipe Mapper for Create Milling Mapper. Required Mods: [create]
		enabled = false

	[CraftingMapper.CreateBASINMapper]
		#ProjectE-Integration Recipe Mapper for Create BASINMapper. Required Mods: [create]
		enabled = false

	[CraftingMapper.ExtendedCraftingTableMapper]
		#Maps Extended Crafting Table recipes
		enabled = false

	[CraftingMapper.PneumaticCraftExplosionCraftingMapper]
		#ProjectE-Integration Recipe Mapper for Pneumatic Craft Explosion Crafting Mapper. Required Mods: [pneumaticcraft] NOTE: Disabled by default because this mapper ignore loss rate.
		enabled = false

	[CraftingMapper.MekChemicalCrystallizer]
		#Maps Mekanism crystallizing recipes.
		enabled = false

	[CraftingMapper.ArsNouveauGlyphMapper]
		#ProjectE-Integration Recipe Mapper for Ars Nouveau Glyph Mapper. Required Mods: [ars_nouveau]
		enabled = true

	[CraftingMapper.MekMetallurgicInfuser]
		#Maps Mekanism metallurgic infuser recipes.
		enabled = false

	[CraftingMapper.CreateCompactingMapper]
		#ProjectE-Integration Recipe Mapper for Create Compacting Mapper. Required Mods: [create]
		enabled = false

	[CraftingMapper.CreateSandpaperPolishingMapper]
		#ProjectE-Integration Recipe Mapper for Create Sandpaper Polishing Mapper. Required Mods: [create]
		enabled = false

	[CraftingMapper.FallbackRecipeType]
		#Fallback for default handling of recipes that extend ICraftingRecipe, AbstractCookingRecipe, SingleItemRecipe, or SmithingRecipe. This will catch modded extensions of the vanilla recipe classes, and if the VanillaRecipeTypes mapper is disabled, this mapper will still catch the vanilla recipes.
		enabled = false

	[CraftingMapper.VanillaRecipeTypes]
		#Maps the different vanilla recipe types.
		enabled = false

	[CraftingMapper.BotaniaManaInfusionMapper]
		#ProjectE-Integration Recipe Mapper for Botania Mana Infusion Mapper. Required Mods: [botania]
		enabled = false

	[CraftingMapper."Avaritia Extreme"]
		#Maps avaritia recipes.
		enabled = true

	[CraftingMapper.IndustrialForegoingDissolutionChamberMapper]
		#ProjectE-Integration Recipe Mapper for Industrial Foregoing Dissolution Chamber Mapper. Required Mods: [industrialforegoing]
		enabled = false

	[CraftingMapper.MekRotary]
		#Maps Mekanism rotary condensentrator recipes.
		enabled = false

	[CraftingMapper.ImmersiveEngineeringCokeOvenMapper]
		#ProjectE-Integration Recipe Mapper for Immersive Engineering Coke Oven Mapper. Required Mods: [immersiveengineering]
		enabled = true

	[CraftingMapper.MekItemStackToPigment]
		#Maps Mekanism item stack to pigment recipes. (Pigment Extracting)
		enabled = false

	[CraftingMapper.DraconicEvolutionFusionMapper]
		#ProjectE-Integration Recipe Mapper for Draconic Evolution Fusion Mapper. Required Mods: [draconicevolution]
		enabled = false

	[CraftingMapper.ExtendedCraftingCombinationMapper]
		#Maps Extended Crafting Combination recipes
		enabled = false

	[CraftingMapper.MekItemStackGasToItemStack]
		#Maps Mekanism Machine recipes that go from item, gas to item. (Compressing, Purifying, Injecting)
		enabled = false

	[CraftingMapper.BotaniaRuneAlterMapper]
		#ProjectE-Integration Recipe Mapper for Botania Rune Alter Mapper. Required Mods: [botania]
		enabled = false

	[CraftingMapper.ImmersiveEngineeringCrusherMapper]
		#ProjectE-Integration Recipe Mapper for Immersive Engineering Crusher Mapper. Required Mods: [immersiveengineering]
		enabled = true

	[CraftingMapper.ImmersiveEngineeringAlloyMapper]
		#ProjectE-Integration Recipe Mapper for Immersive Engineering Alloy Mapper. Required Mods: [immersiveengineering]
		enabled = true

	[CraftingMapper.CreateHauntingMapper]
		#ProjectE-Integration Recipe Mapper for Create Haunting Mapper. Required Mods: [create]
		enabled = false

	[CraftingMapper.CreateMechanicalCraftingMapper]
		#ProjectE-Integration Recipe Mapper for Create Mechanical Crafting Mapper. Required Mods: [create]
		enabled = false

	[CraftingMapper.BotaniaPetalMapper]
		#ProjectE-Integration Recipe Mapper for Botania Petal Mapper. Required Mods: [botania]
		enabled = false

	[CraftingMapper.CreatePressingMapper]
		#ProjectE-Integration Recipe Mapper for Create Pressing Mapper. Required Mods: [create]
		enabled = false

	[CraftingMapper.MekPressurizedReaction]
		#Maps Mekanism pressurized reaction recipes.
		enabled = false

	[CraftingMapper.TinkersConstructMeltingMapper]
		#ProjectE-Integration Recipe Mapper for Tinkers Construct Melting Mapper. Required Mods: [tconstruct]
		enabled = false

	[CraftingMapper.MekItemStackToGas]
		#Maps Mekanism item stack to gas recipes. (Gas conversion, Oxidizing)
		enabled = false

	[CraftingMapper.MekPigmentMixer]
		#Maps Mekanism pigment mixer recipes.
		enabled = false

	[CraftingMapper.ArsNouveauImbuementMapper]
		#ProjectE-Integration Recipe Mapper for Ars Nouveau Imbuement Mapper. Required Mods: [ars_nouveau]
		enabled = true

	[CraftingMapper.IndustrialForegoingCrusherMapper]
		#ProjectE-Integration Recipe Mapper for Industrial Foregoing Crusher Mapper. Required Mods: [industrialforegoing]
		enabled = false

	[CraftingMapper.TinkersConstructAlloyingMapper]
		#ProjectE-Integration Recipe Mapper for Tinkers Construct Alloying Mapper. Required Mods: [tconstruct]
		enabled = false

	[CraftingMapper.AvaritiaExtremeCraftingMapper]
		#ProjectE-Integration Recipe Mapper for Avaritia Extreme Crafting Mapper. Required Mods: [avaritia]
		enabled = false

	[CraftingMapper.CreateItemApplicationMapper]
		#ProjectE-Integration Recipe Mapper for Create Item Application Mapper. Required Mods: [create]
		enabled = false

	[CraftingMapper.PneumaticCraftRefineryMapper]
		#ProjectE-Integration Recipe Mapper for Pneumatic Craft Refinery Mapper. Required Mods: [pneumaticcraft]
		enabled = true

	[CraftingMapper.PneumaticCraftAssemblyMapper]
		#ProjectE-Integration Recipe Mapper for Pneumatic Craft Assembly Mapper. Required Mods: [pneumaticcraft]
		enabled = true

	[CraftingMapper.PneumaticCraftAmadronOfferMapper]
		#ProjectE-Integration Recipe Mapper for Pneumatic Craft Amadron Offer Mapper. Required Mods: [pneumaticcraft]
		enabled = true

	[CraftingMapper.CreateSequencedAssemblyMapper]
		#ProjectE-Integration Recipe Mapper for Create Sequenced Assembly Mapper. Required Mods: [create]
		enabled = false

	[CraftingMapper.MekElectrolysis]
		#Maps Mekanism electrolytic separator recipes.
		enabled = false

	[CraftingMapper.MekGasToGas]
		#Maps Mekanism activating and centrifuging recipes.
		enabled = false

	[CraftingMapper.MekItemStackToItemStack]
		#Maps Mekanism Machine recipes that go from item to item. (Crushing, Enriching, Smelting)
		enabled = false

	[CraftingMapper.ImmersiveEngineeringBlastFurnaceMapper]
		#ProjectE-Integration Recipe Mapper for Immersive Engineering Blast Furnace Mapper. Required Mods: [immersiveengineering]
		enabled = true

	[CraftingMapper.IndustrialForegoingStoneWorksGenerateMapper]
		#ProjectE-Integration Recipe Mapper for Industrial Foregoing Stone Works Generate Mapper. Required Mods: [industrialforegoing] NOTE: Disabled by default.
		enabled = false

	[CraftingMapper.BotaniaTerraPlateMapper]
		#ProjectE-Integration Recipe Mapper for Botania Terra Plate Mapper. Required Mods: [botania]
		enabled = false

	[CraftingMapper.CreateCUTTINGMapper]
		#ProjectE-Integration Recipe Mapper for Create CUTTINGMapper. Required Mods: [create]
		enabled = false

	[CraftingMapper.MekSawmill]
		#Maps Mekanism sawmill recipes. (Disabled by default, due to causing various EMC values to be removed pertaining to charcoal/wood)
		enabled = false

	[CraftingMapper.IceAndFireDragonForgeMapper]
		#Recipe mapper for Ice and Fire DragonForge recipes
		enabled = true

	[CraftingMapper.MekCombiner]
		#Maps Mekanism combiner recipes.
		enabled = false

	[CraftingMapper.ExtendedCraftingCompressorMapper]
		#ProjectE-Integration Recipe Mapper for Extended Crafting Compressor Mapper. Required Mods: [extendedcrafting]
		enabled = false

	[CraftingMapper.BotaniaPureDaisyMapper]
		#ProjectE-Integration Recipe Mapper for Botania Pure Daisy Mapper. Required Mods: [botania]
		enabled = false

	[CraftingMapper.TinkersConstructCastingMapper]
		#ProjectE-Integration Recipe Mapper for Tinkers Construct Casting Mapper. Required Mods: [tconstruct]
		enabled = false

	[CraftingMapper.MekFluidToFluid]
		#Maps Mekanism evaporating recipes.
		enabled = false

	[CraftingMapper.Smithing]
		#Maps smithing recipes.
		enabled = false

	[CraftingMapper.CreateSplashingMapper]
		#ProjectE-Integration Recipe Mapper for Create Splashing Mapper. Required Mods: [create]
		enabled = false

	[CraftingMapper.CreateCuttingMapper]
		#ProjectE-Integration Recipe Mapper for Create Cutting Mapper. Required Mods: [create]
		enabled = false

	[CraftingMapper.ImmersiveEngineeringSawmillMapper]
		#ProjectE-Integration Recipe Mapper for Immersive Engineering Sawmill Mapper. Required Mods: [immersiveengineering]
		enabled = true

	[CraftingMapper.MekItemStackToInfuseType]
		#Maps Mekanism item stack to infuse type conversion recipes.
		enabled = false

	[CraftingMapper."Avaritia Compressor"]
		#Maps avaritia recipes.
		enabled = true

	[CraftingMapper.AvaritiaCompressorMapper]
		#ProjectE-Integration Recipe Mapper for Avaritia Compressor Mapper. Required Mods: [avaritia]
		enabled = false

	[CraftingMapper.PneumaticCraftPressureChamberMapper]
		#ProjectE-Integration Recipe Mapper for Pneumatic Craft Pressure Chamber Mapper. Required Mods: [pneumaticcraft]
		enabled = true

	[CraftingMapper.ArsNouveauCrushMapper]
		#ProjectE-Integration Recipe Mapper for Ars Nouveau Crush Mapper. Required Mods: [ars_nouveau]
		enabled = true

	[CraftingMapper.PneumaticCraftHeatFrameCoolingMapper]
		#ProjectE-Integration Recipe Mapper for Pneumatic Craft Heat Frame Cooling Mapper. Required Mods: [pneumaticcraft]
		enabled = true

	[CraftingMapper.AppliedEnergisticsInscriberMapper]
		#ProjectE-Integration Recipe Mapper for Applied Energistics Inscriber Mapper. Required Mods: [ae2]
		enabled = false

	[CraftingMapper.MekDissolution]
		#Maps Mekanism dissolution recipes.
		enabled = false

	[CraftingMapper.ImmersiveEngineeringMixerMapper]
		#ProjectE-Integration Recipe Mapper for Immersive Engineering Mixer Mapper. Required Mods: [immersiveengineering]
		enabled = true

	[CraftingMapper.MekFluidSlurryToSlurry]
		#Maps Mekanism washing recipes.
		enabled = false

	[CraftingMapper.PneumaticCraftThermopneumaticProcessingPlantMapper]
		#ProjectE-Integration Recipe Mapper for Pneumatic Craft Thermopneumatic Processing Plant Mapper. Required Mods: [pneumaticcraft]
		enabled = true

	[CraftingMapper.PsiTrickMapper]
		#ProjectE-Integration Recipe Mapper for Psi Trick Mapper. Required Mods: [psi]
		enabled = false

	[CraftingMapper.ExtendedCraftingEnderCrafterMapper]
		#Maps extended crafting Ender Crafter recipes
		enabled = false

	[CraftingMapper.CreateCrushingMapper]
		#ProjectE-Integration Recipe Mapper for Create Crushing Mapper. Required Mods: [create]
		enabled = false

	[CraftingMapper.ImmersiveEngineeringMetalPressMapper]
		#ProjectE-Integration Recipe Mapper for Immersive Engineering Metal Press Mapper. Required Mods: [immersiveengineering]
		enabled = true

	[CraftingMapper.ArsNouveauEnchantingApparatusMapper]
		#ProjectE-Integration Recipe Mapper for Ars Nouveau Enchanting Apparatus Mapper. Required Mods: [ars_nouveau]
		enabled = true

[permissions]

	[permissions.avaritia]
		#Allow mod 'avaritia' to set and or remove values for mod 'minecraft'. Options: [both, set, remove, none]
		minecraft = "both"
		#Allow mod 'avaritia' to set and or remove values for mod 'avaritia'. Options: [both, set, remove, none]
		avaritia = "both"

[APICustomEMCMapper]

	[APICustomEMCMapper.priority]
		#Priority for this mod
		avaritia = 1

[enabledMappers]
	#Set EMC=0 for everything in the forge:raw_materials tag
	RawOresBlacklistMapper = true
	#Add Conversions for Crafting Recipes gathered from net.minecraft.item.crafting.RecipeManager
	CraftingMapper = true
	#Adds back and forth conversions of objects and their Tag variant. (EMC values assigned to tags will not behave properly if this mapper is disabled)
	TagMapper = true
	#Add Conversions for Brewing Recipes
	BrewingMapper = true
	#Allows setting EMC values through CraftTweaker. This behaves similarly to if someone used the custom emc file instead.
	CrTCustomEMCMapper = true
	#Recipe mapper for custom recipes that don't implement IRecipe
	ProjectEIntegrationRecipeMapper = true
	#Loads json files within datapacks (data/<domain>/pe_custom_conversions/*.json) to add values and conversions
	CustomConversionMapper = true
	#Allows adding custom conversions through CraftTweaker. This behaves similarly to if someone used a custom conversion file instead.
	CrTConversionEMCMapper = true
	#Set EMC=0 for everything in the forge:ores tag
	OresBlacklistMapper = true
	#Add Conversions for all lingering potions to arrow recipes
	TippedArrowMapper = true
	#Add Conversions for all weathered copper variants
	WeatheredCopperMapper = true
	#Uses the `custom_emc.json` File to add EMC values.
	CustomEMCMapper = true
	#Allows other mods to easily set EMC values using the ProjectEAPI
	APICustomEMCMapper = true

